name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5  # Specify your Terraform version

      - name: Terraform Init
        env:
          name: AWS_SECRET_KEY_ID
          name1: AWS_SECRET_ACCESS_KEY
        run: terraform init

      - name: Terraform Plan
        env:
          name: AWS_SECRET_KEY_ID
          name1: AWS_SECRET_ACCESS_KEY
        run: terraform plan

      - name: Terraform Apply
        env:
          name: AWS_SECRET_KEY_ID
          name1: AWS_SECRET_ACCESS_KEY
        run: terraform apply -auto-approve
